sudo: required
services:
  - docker

before_install:
  - docker build -t amohamedd74/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true amohamedd74/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-590183740433"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"